source 'https://rubygems.org'
gem 'rails', '~> 7.1.0'
gem 'sqlite3', '~> 1.4'
gem 'devise'
gem 'good_job'
gem 'tailwindcss-rails'
gem 'importmap-rails'
gem 'jbuilder'
gem 'faker'
gem 'tzinfo-data', platforms: :windows
gem 'puma', '~> 6.4'
gem 'propshaft'
gem 'csv'
gem 'turbo-rails'
gem 'fiddle'