# File: config/features.yml
# Path: /config/features.yml
current:
  - Stations lists with search & status filters
  - Manual ping with live latency result
  - CSV import for stations
  - Tailwind UI theming
  - Last ping timestamp display
  - Station editing (name, URL, tags, monitoring options)

planned:
  - add nested grouping of stations on station list page (e.g. by active (monitoring), client, project, etc.)
  - Test/debug Background daemon server data ingest
  - Historical data modal (zoom/pan + export) (untested)
  - Direct logger status table ingest
  - fix the "collage" of colours in the station cards
  - add "request feature" button to "features" page
  - Finish darkmode theming
  - Project / client based station filters
  - Station tags management (add/edit/delete)
  - Tidy up stations cards formatting
  - System health dashboard with sparkline mini-charts
  - Alerting to Teams & Email with thresholds
  - Admin users & secure storage (tokens, file paths)
  - Export stations to CSV (UI action)
  - Settings page for system-wide config (from sidebar)
  - Dockerfile for easy deployment